name: cardreader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  share_plus: ^7.2.1

flutter:
  uses-material-design: true
